package dl.equipmentCalculator.model.exception

import dl.equipmentCalculator.model.ExceptionType.Companion.INVALID_ITEM_COMBINATION

class InvalidItemCombinationException : RuntimeException(INVALID_ITEM_COMBINATION)
